export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_PROCESS = "ADD_CART_PROCESS";
export const DECREASE_CART = "DECREASE_CART";
export const INCREASE_CART = "INCREASE_CART";
export const DELETE_CART = "DELETE_CART";
