// get all products
export const GET_ALL_PRODUCTS_PROCESS = "GET_ALL_PRODUCTS_PROCESS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

// get product by id
export const GET_PRODUCT_BY_ID_PROCESS = "GET_PRODUCT_BY_ID_PROCESS";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

// get product by category
export const GET_PRODUCT_BY_CATEGORY_PROCESS =
  "GET_PRODUCT_BY_CATEGORY_PROCESS";
export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  "GET_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_FAIL = "GET_PRODUCT_BY_CATEGORY_FAIL";

// get all categories
export const GET_ALL_CATEGORIES_PROCESS = "GET_ALL_CATEGORIES_PROCESS";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

// get product by search
export const SEARCH_PROCESS = "SEARCH_PROCESS";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

// return the value of product title as a search result on input
export const INPUT_RESULT_PROCESS = "INPUT_RESULT_PROCESS ";
export const INPUT_RESULT_FAIL = "INPUT_RESULT_FAIL ";
export const INPUT_RESULT_SUCCESS = "INPUT_RESULT_SUCCESS ";

// search a product by name and filter it by rating and price
export const SEARCH_RESULT_PROCESS = "SEARCH_RESULT_PROCESS ";
export const SEARCH_RESULT_FAIL = "SEARCH_RESULT_FAIL ";
export const SEARCH_RESULT_SUCCESS = "SEARCH_RESULT_SUCCESS ";
