// get all products
export const GET_ALL_PRODUCTS_PROCESS = "GET_ALL_PRODUCTS_PROCESS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

// get product by id
export const GET_PRODUCT_BY_ID_PROCESS = "GET_PRODUCT_BY_ID_PROCESS";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

// get product by category
export const GET_PRODUCT_BY_CATEGORY_PROCESS =
  "GET_PRODUCT_BY_CATEGORY_PROCESS";
export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  "GET_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_FAIL = "GET_PRODUCT_BY_CATEGORY_FAIL";

// get all categories
export const GET_ALL_CATEGORIES_PROCESS = "GET_ALL_CATEGORIES_PROCESS";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";
